<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta charset="utf-8" />

		<meta name="description" content="Common form elements and layouts" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

		<!-- bootstrap & fontawesome -->
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/bootstrap.min.css" />
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/font-awesome.min.css" />

		<!-- page specific plugin styles -->
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/jquery-ui.custom.min.css" />
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/chosen.css" />
		<!-- text fonts -->
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/ace-fonts.css" />

		<!-- ace styles -->
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/ace.min.css" id="main-ace-style" />

		<!--[if lte IE 9]>
			<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/ace-part2.min.css" />
		<![endif]-->
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/ace-skins.min.css" />
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/ace-rtl.min.css" />

		<!--[if lte IE 9]>
		  <link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/ace-ie.min.css" />
		<![endif]-->

		<!-- inline styles related to this page -->

		<!-- ace settings handler -->
		<script src="<?php echo $this->basePath()."/" ?>assets/js/ace-extra.min.js"></script>


	</head>

	<body class="no-skin">

		<!-- /section:basics/navbar.layout -->
		<div class="main-container" id="main-container">
			<script type="text/javascript">
				try{ace.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

			<!-- /section:basics/sidebar -->
			<div class="main-content">

				<!-- /section:basics/content.breadcrumbs -->
				<div class="page-content">


					<!-- /section:settings.box -->
					<div class="page-content-area">


						<div class="row">
							<div class="col-xs-12">
                                                         <!-- PAGE CONTENT INI -->


        <script src="<?php echo $this->basePath()."/" ?>assets/js/jquery-1.9.1.js"></script>
        <script src="<?php echo $this->basePath()."/" ?>assets/js/jquery-ui.js"></script>

        <script src="<?php echo $this->basePath()."/" ?>assets/js/jquery-ui-1.10.2.custom.min.js"></script>                                                                


<?php echo $this->content; ?>                                                        
                                                        </div><!-- PAGE CONTENT ENDS -->

						</div><!-- /.row -->
					</div><!-- /.page-content-area -->
				</div><!-- /.page-content -->
			</div><!-- /.main-content -->



		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<script type="text/javascript">
			if('ontouchstart' in document.documentElement) document.write("<script src='<?php echo $this->basePath()."/" ?>assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
		</script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/bootstrap.min.js"></script>

		<!-- page specific plugin scripts -->


		<script src="<?php echo $this->basePath()."/" ?>assets/js/jquery-ui.custom.min.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/jquery.ui.touch-punch.min.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/chosen.jquery.min.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/date-time/moment.min.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/jquery.knob.min.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/jquery.autosize.min.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/jquery.inputlimiter.1.3.1.min.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/jquery.maskedinput.min.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/bootstrap-tag.min.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/typeahead.jquery.min.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/jquery.dataTables.min.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/jquery.dataTables.bootstrap.js"></script>
                
		<!-- ace scripts -->
		<script src="<?php echo $this->basePath()."/" ?>assets/js/ace-elements.min.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/ace.min.js"></script>

		<!-- the following scripts are used in demo only for onpage help and you don't need them -->
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/ace.onpage-help.css" />
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>docs/assets/js/themes/sunburst.css" />

		<script type="text/javascript"> ace.vars['base'] = '..'; </script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/ace/elements.onpage-help.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>assets/js/ace/ace.onpage-help.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>docs/assets/js/rainbow.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>docs/assets/js/language/generic.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>docs/assets/js/language/html.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>docs/assets/js/language/css.js"></script>
		<script src="<?php echo $this->basePath()."/" ?>docs/assets/js/language/javascript.js"></script>
	</body>
</html>
