		<!-- bootstrap & fontawesome -->
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/bootstrap.min.css" />
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/font-awesome.min.css" />

		<!-- page specific plugin styles -->
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/jquery-ui.custom.min.css" />
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/fullcalendar.css" />

		<!-- text fonts -->
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/ace-fonts.css" />

		<!-- ace styles -->
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/ace.min.css" id="main-ace-style" />

		<!--[if lte IE 9]>
			<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/ace-part2.min.css" />
		<![endif]-->
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/ace-skins.min.css" />
		<link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/ace-rtl.min.css" />

		<!--[if lte IE 9]>
		  <link rel="stylesheet" href="<?php echo $this->basePath()."/" ?>assets/css/ace-ie.min.css" />
		<![endif]-->

		<!-- inline styles related to this page -->

		<!-- ace settings handler -->
		<script src="<?php echo $this->basePath()."/" ?>assets/js/ace-extra.min.js"></script>