<ul class="nav nav-pills">
    <li id="prog<?php echo $this->idE ?>"><a href="#">Programación</a></li>
</ul>

<script>
$(function () {
  $("#prog<?php echo $this->idE ?>").click(function () {  
        var b = <?php echo $this->idE ?>;
        var parametros = {
            "id"  : b,                
        };            
        // Validar que no genere 2 veces la misma nomina         
        $.ajax({
            data:  parametros,
            url:   '<?php echo $this->basePath() ?>/talentohumano/programa/listp',
            type:  'post',
            beforeSend: function () {
                $("#resultadoP").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>Buscando programaciones, por favor espere...');
            },
            success:  function (response) {
//                alert('Nomina generada de forma correcta');
                $("#resultadoP").html(response);
                $( "#calendario" ).dialog( "open" );
                //location.href='<?php echo $this->basePath() ?><?php echo $this->lin?>';                    
            }            

        }); // Ajax envio de datos       

      });// Generacion de nomina
  })
</script>


<div id="calendario" title="Calendario">    
	<div id="resultadoP"></div>
</div>



<script>
  $(function() {
    $( "#calendario" ).dialog({
      autoOpen: false,
      height: 700,
      width: 900,      
      show: {
        effect: "blind",
        duration: 1000
      },
      hide: {
        effect: "explode",
        duration: 1000
      },
      buttons: {
          "Agregar estudio realizado": function() {          
           var id      = $("#id").val();
           var idNest  = $("#idNest2").val();
           var inst    = $("#comenN").val();
           var titulo  = $("#comenN2").val();
                      
           if($("#comenN").val().length < 1) {  
              alert("Debe escribir el nombre de la institución");  
              return false;  
            }  

           if($("#comenN2").val().length < 1) {  
              alert("Debe escribir el titulo obtenido");  
              return false;  
            }  
            $( "#formGuaradarE" ).submit();          
 
          },
          Cancel: function() {
          $( this ).dialog( "close" );          
        }
      }
    });  

  });
</script>