<ul class="nav nav-list2">
 <li><!-- TALENTO HUMANO-->
  <a href="#" class="dropdown-toggle" ><i class="icon-group"></i><span>Talento humano</span><b class="arrow icon-angle-down"></b></a>
  <ul class="submenu" style="display:none;" >
    <li><a href="#" class="dropdown-toggle"><i class="icon-double-angle-right"></i> Documentos</a>
     <ul class="submenu" >
       <li><a href="#" class="dropdown-toggle">Contratacion</a>
       <li><a href="<?php echo $this->basePath() ?>/talentohumano/solcon/list"> 1. Solicitud de la contratacion</a></li>                                
       <li><a href="<?php echo $this->basePath() ?>/talentohumano/selper/list">2. Seleccion de personal</a></li>                                                                   
       <li><a href="<?php echo $this->basePath() ?>/talentohumano/inicon/list">3. Proceso de contratacion</a></li>                                   
       <li><a href="<?php echo $this->basePath() ?>/talentohumano/admcon/list">4. Administracion de contratacion</a></li>                                                                        
     </ul>
    </li>
    <li><a href="#"><i class="icon-double-angle-right"></i> Informes</a><!-- Reportes -->

    </li><!-- Fin reportes -->
    <li><a href="#"><i class="icon-double-angle-right"></i> Maestros</a>
     <ul class="submenu" >      
      <li><a href="<?php echo $this->basePath() ?>/talentohumano/cargos/list">Cargos</a></li>                                
      <li><a href="<?php echo $this->basePath() ?>/talentohumano/aspcar/list">Aspectos de cargos</a></li>                                                                   
      <li><a href="<?php echo $this->basePath() ?>/talentohumano/naspcar/list">Niveles de aspectos</a></li>                                                                                                           
      <li><a href="<?php echo $this->basePath() ?>/talentohumano/lcheq/list">Lista de chequeo</a></li>                                   
      <li><a href="<?php echo $this->basePath() ?>/talentohumano/tipcon/list">Tipos de contrataciones</a></li>                                                                        
      <li><a href="<?php echo $this->basePath() ?>/talentohumano/sedes/list" >Sedes</a></li>
      <li><a href="<?php echo $this->basePath() ?>/talentohumano/depar/list" >Departamentos</a></li>                                                                
      <li><a href="<?php echo $this->basePath() ?>/talentohumano/fondos/list" >Fondos prestacionales y seguridad social</a></li>                                
      <li><a href="<?php echo $this->basePath() ?>/talentohumano/formch/list" >Form. lista de cheque</a></li>                              
     </ul>
    </li>
  </ul>
</li><!-- FIN TALENTO HUMANO-->

<li><!-- ADMINISTRACION DEL PERSONAL-->
 <a href="#" class="dropdown-toggle" ><i class="icon-desktop"></i><span>Administración</span><b class="arrow icon-angle-down"></b></a>
  <ul class="submenu" >
   <li><a href="#" class="dropdown-toggle"><i class="icon-double-angle-right"></i> Documentos</a>
    <ul class="submenu">
     <li><a href="ad_c_soli_capa.php" >Solicitud de capacitaciones</a></li>
     <li><a href="ad_area_capa.php" >Area de capacitaciones</a></li>  
     <li><a href="ad_doc_dotaciones.php" >Entrega de dotaciones</a></li>                   		        
    </ul>  
   </li>
   <li><a href="#"><i class="icon-double-angle-right"></i> Informes</a></li>
   <li><a href="#"><i class="icon-double-angle-right"></i> Maestros</a>
    <ul class="submenu" >
      <li><a href="ad_grup_dot.php" >Grupo de dotaciones</a></li>
      <li><a href="ad_dotaciones.php" >Dotaciones</a></li>                   		        
      <li><a href="ad_lin_dot.php" >Lineas de dotaciones</a></li>                   		                                        
    </ul>
   </li>
  </ul>
 </li><!-- FIN ADIMISITRACION DEL PERSONAL-->
 
 
 <li><!-- NOMINA-->
 <a href="#" class="dropdown-toggle" ><i class="icon-calendar"></i><span>Nomina</span><b class="arrow icon-angle-down"></b></a>
  <ul class="submenu" >
   <li><a href="#" class="dropdown-toggle"><i class="icon-double-angle-right"></i> Documentos</a>
    <ul class="submenu">     
     <li><a href="<?php echo $this->basePath() ?>/nomina/gnomina/list" >Generacion de nomina</a></li>
     <li><a href="<?php echo $this->basePath() ?>/nomina/nomina/list" >Novedades en nomina</a></li>
     <li><a href="<?php echo $this->basePath() ?>/nomina/cnomina/list" >Cierre de nominas activas</a></li>
     <li><a href="<?php echo $this->basePath() ?>/nomina/presta/list">Prestamos</a></li>                                
    </ul>  
   </li>
   <li><a href="#"><i class="icon-double-angle-right"></i> Informes</a><!-- Reportes -->
     <ul class="submenu" >      
       <li><a href="<?php echo $this->basePath() ?>/nomina/infnomina/list">Nominas activas</a></li>                                       
     </ul> 
    </li><!-- Fin reportes -->       
       
   </li>
   <li><a href="#"><i class="icon-double-angle-right"></i> Maestros</a>
    <ul class="submenu" >        
      <li><a href="<?php echo $this->basePath() ?>/nomina/empleados/list" >Empleados</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/cencostos/list" >Centros de costos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/conceptos/list" >Conceptos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/procesos/list" >Procesos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/grupos/list" >Grupos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/subgrupos/list" >Sub grupos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/niveles/list" >Niveles</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/prefijo/list" >Prefijos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/tipcalen/list" >Calendarios</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/tipnomina/list" >Tipos de nomina</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/tipauto/list" >Tipos de Automaticos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/tipemp/list" >Tipos de empleados</a></li>      
      <li><a href="<?php echo $this->basePath() ?>/nomina/auto/list" >Otros automaticos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/formulas/list" >Formulaciones</a></li>
    </ul>
   </li>
  </ul>
 </li><!-- FIN NOMINA-->
 
 
  <li><!-- CONFIGURACIONES-->
 <a href="#" class="dropdown-toggle" ><i class="icon-cogs"></i><span>Configuraciones</span><b class="arrow icon-angle-down"></b></a>
  <ul class="submenu" >
   <li><a href="#" class="dropdown-toggle"><i class="icon-double-angle-right"></i> Parametrizaciones</a>
    <ul class="submenu">     
     <li><a href="<?php echo $this->basePath() ?>/nomina/gnomina/list" >Generales</a></li>
     <li><a href="<?php echo $this->basePath() ?>/conf/gnomina/list" >Nomina</a></li>
    </ul>  
   </li>
   

  </ul>
 </li><!-- FIN CONFIGURACIONES-->

</ul><!--/.nav-list-->


