
<ul id='con_menu' class='nav nav-list2'>
  
 <li><!-- NOMINA-->
 <a href="#" class="dropdown-toggle" ><i class="icon-calendar"></i><span>Nomina</span><b class="arrow icon-angle-down"></b></a>
  <ul >
   <li><a href="#" class="dropdown-toggle"><i class="icon-double-angle-right"></i> Documentos</a>
    <ul>     
     <li><a href="<?php echo $this->basePath() ?>/nomina/gnomina/list" >Generacion de nomina</a></li>
     <li><a href="<?php echo $this->basePath() ?>/nomina/nomina/list" >Novedades en nomina</a></li>
     <li><a href="<?php echo $this->basePath() ?>/nomina/cnomina/list" >Cierre de nominas activas</a></li>
     <li><a href="<?php echo $this->basePath() ?>/nomina/presta/list">Prestamos</a></li>                                
    </ul>  
   </li>
   <li><a href="#"><i class="icon-double-angle-right"></i> Informes</a><!-- Reportes -->
     <ul>      
       <li><a href="<?php echo $this->basePath() ?>/nomina/infnomina/list">Nominas activas</a></li>                                       
     </ul> 
    </li><!-- Fin reportes -->       
       
   </li>
   <li><a href="#"><i class="icon-double-angle-right"></i> Maestros</a>
    <ul>        
      <li><a href="<?php echo $this->basePath() ?>/nomina/empleados/list" >Empleados</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/cencostos/list" >Centros de costos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/conceptos/list" >Conceptos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/procesos/list" >Procesos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/grupos/list" >Grupos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/subgrupos/list" >Sub grupos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/niveles/list" >Niveles</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/prefijo/list" >Prefijos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/tipcalen/list" >Calendarios</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/tipnomina/list" >Tipos de nomina</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/tipauto/list" >Tipos de Automaticos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/tipemp/list" >Tipos de empleados</a></li>      
      <li><a href="<?php echo $this->basePath() ?>/nomina/auto/list" >Otros automaticos</a></li>
      <li><a href="<?php echo $this->basePath() ?>/nomina/formulas/list" >Formulaciones</a></li>
    </ul>
   </li>
  </ul>
 </li><!-- FIN NOMINA-->
 


</ul><!--/.nav-list-->


